"""Add event_id to participants

Revision ID: 9f0a96ab4c8a
Revises: ce0c8920f021
Create Date: 2023-09-05 14:11:37.686390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0a96ab4c8a'
down_revision = 'ce0c8920f021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'participants', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    # ### end Alembic commands ###
